# Generated by Django 4.2.3 on 2025-01-19 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor'),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AlterUniqueTogether(
            name='mentoravailability',
            unique_together={('mentor', 'availability')},
        ),
    ]
