# Generated by Django 4.2.3 on 2024-12-26 21:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
