repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies:
            - flake8-black>=0.2.2
        args: ["--max-line-length", "120"]
        language_version: python3
        entry: flake8 --extend-ignore=E741,E203
