# Generated by Django 4.2.3 on 2025-01-20 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='major',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='university',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the seniority e.g. Tech industry: Entry LevelIntermediateSenior, ManagerDirector, LeadExecutive, Founder', max_length=255)),  # noqa: E501
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.industry')),
            ],
            options={
                'unique_together': {('industry', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='seniority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.seniority', verbose_name='Seniority'),  # noqa: E501
        ),
    ]
