# Generated by Django 4.2.3 on 2024-12-26 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_initial'),
        ('mentors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.expertise', verbose_name='Expertise'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='major',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experienceskill',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.experience', verbose_name='Experience'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experienceskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.skill', verbose_name='Skill'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experienceskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.company', verbose_name='Company'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experience',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor', verbose_name='Mentor'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.role', verbose_name='Role'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.major', verbose_name='Major'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='education',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor', verbose_name='Mentor'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.university', verbose_name='university'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='certificate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.company', verbose_name='Company'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='Credential URL'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='certificate',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor', verbose_name='Mentor'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),  # noqa: E501
        ),
    ]
