# Generated by Django 4.2.3 on 2025-01-20 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0002_alter_company_user_alter_expertise_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='mentors.expertise', verbose_name='Expertise'),  # noqa: E501
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together={('expertise', 'user')},
        ),
    ]
