# Generated by Django 4.2.3 on 2025-01-22 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0003_alter_mentor_expertise_alter_mentor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),  # noqa: E501
        ),
    ]
