# Generated by Django 4.2.3 on 2025-01-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentor_unique_together_alter_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='market_qualified_limitation',
            field=models.IntegerField(default=10, help_text='Industry market qualified limitation'),
        ),
    ]
