# Generated by Django 4.2.3 on 2024-12-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='total_month',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='total_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='total_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='total_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='total_month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='total_year',
        ),
    ]
