# Generated by Django 4.2.3 on 2024-01-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('mentors', '0004_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Credential ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='Credential URL'),  # noqa F501
        ),
    ]
