# Generated by Django 4.2.3 on 2024-01-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_country'),
        ('mentors', '0005_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'), # noqa F501
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'), # noqa F501
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'), # noqa F501
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, help_text='If you have critical id for your certificate please insert here', max_length=50, null=True, unique=True, verbose_name='Credential ID'), # noqa F501
        ),
    ]
