# Generated by Django 4.2.3 on 2024-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_certificate_location_education_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='total_month',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total month'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='total_year',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total year'),
        ),
        migrations.AddField(
            model_name='education',
            name='total_month',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total month'),
        ),
        migrations.AddField(
            model_name='education',
            name='total_year',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total year'),
        ),
        migrations.AddField(
            model_name='experience',
            name='total_month',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total month'),
        ),
        migrations.AddField(
            model_name='experience',
            name='total_year',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True, verbose_name='Total year'),
        ),
    ]
