# Generated by Django 4.2.3 on 2024-01-19 15:15

import django.db.models.deletion
from django.db import migrations

import utilities.db.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_celery_beat_functions'),
        ('users', '0004_alter_userprofile_last_name_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=utilities.db.fields.file_field.FileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='files.filemodel',
                verbose_name='Avatar'),
        ),
    ]
