# Generated by Django 4.2.3 on 2024-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('blank', models.BooleanField(default=False, verbose_name='Blank')),
                ('in_app', models.BooleanField(default=False, help_text='Open in app, like webview in application', verbose_name='In app')),  # noqa F501
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('url', models.URLField(verbose_name='URL')),
                ('variable', models.CharField(blank=True, help_text='You can use the following variables in your page link to pass user information via URL parameters. {{USER_ID}} {{USER_NAME}} {{USER_EMAIL}}', max_length=255, verbose_name='Variable')),  # noqa F501
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
